# Generated by Django 2.2.6 on 2019-11-17 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_name', models.CharField(max_length=256)),
                ('TRC_file', models.FileField(upload_to='documents/')),
                ('skiprows', models.CharField(max_length=256)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='qrOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TRC_file', models.TextField()),
                ('output1', models.TextField()),
                ('output2', models.TextField()),
                ('doc_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QRvisualisation.FileInput')),
            ],
        ),
    ]
