# Generated by Django 2.2.6 on 2019-11-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRvisualisation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceZonalFileInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_quarters', models.CharField(max_length=256)),
                ('line', models.CharField(choices=[('C138', 'C138'), ('C195', 'C195')], default='C138', max_length=4)),
            ],
        ),
    ]
